remote: true
hybrid: true
onsite: true

experience_level:
  internship: false
  entry: false 
  associate: false 
  mid_senior_level: false 
  director: true 
  executive: true 

job_types:
  full_time: true
  contract: false
  part_time: false
  temporary: false 
  internship: false
  other: false
  volunteer: false 

date:
  all_time: false
  month: false
  week: false
  24_hours: true

positions:
  - Head of Professional Services
  - VP of Professional Services
  - VP Professional Services
  - Director of Professional Services
  - Director Professional Services

locations:
  - United States 

apply_once_at_company: true

distance: 100

company_blacklist:

title_blacklist:

location_blacklist:

job_applicants_threshold:
  min_applicants: 0
  max_applicants: 30

llm_model_type: openai
llm_model: 'gpt-4o'
llm_api_url: https://api.pawan.krd/cosmosrp/v1'
